# Author: Daniel Benjamin Perez Morales
# GitHub: https://github.com/DanielBenjaminPerezMoralesDev13
# GitLab: https://gitlab.com/DanielBenjaminPerezMoralesDev13
# Email: danielperezdev@proton.me

# Ejemplo de c√≥mo cargar un fichero TOML
# Supongamos que tenemos un fichero llamado 'config.toml' con el siguiente contenido:
[settings]
theme = "dark"
version = 1.0